// <auto-generated />
namespace POS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201306192132266_migrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
